dist: xenial
language: node_js
node_js:
  - '8'
  - '10'
  - '12'

env:
  global:
    - SAUCE_USERNAME: karmarunnerbot
    - secure: "bRVY+hYZwMf1SqVnMyZRJTLD0gN1hLx9/MwO8MM/qBiu3YNjXy49XElfMdzMKN6cZeKTmhcnjmZonbJuI1PQ2t+utGkyjnlVLJ/OlWptreKLzIlcbt4hrdPoTcjmUTwDWq9Ex9cVoYX8AzCasETttpczp3P+s3+vmOUj8z25JyU="

stages:
  - check
  - test

jobs:
  include:
    - name: "Lint code and commit message format"
      stage: check
      node_js: "8"
      script:
        - echo "TRAVIS_COMMIT $TRAVIS_COMMIT"
        - echo "TRAVIS_PULL_REQUEST_SHA $TRAVIS_PULL_REQUEST_SHA"
        - COMMIT_TO_VALIDATE=${TRAVIS_PULL_REQUEST_SHA:-$TRAVIS_COMMIT}
        - echo "COMMIT_TO_VALIDATE $COMMIT_TO_VALIDATE"
        - ./scripts/validate-commit-msg.sh $COMMIT_TO_VALIDATE
        - npm run lint

services:
  - xvfb

addons:
  chrome: stable
  firefox: latest

before_script:
  - export $(openssl aes-256-cbc -pass env:CREDENTIALS_PASS -d -in credentials)

script:
  - npm run init
  - npm run travis
